class MatchMemorableMoment {
  constructor(
    matchForeverId,
    playersInMemorableMoment,
    archetypeOfMemorableMoment,
    memorableMomentEncoded,
    memorableMomentTimestamp,
    memoralMomentAutoGeneratedSass
  ) {
    this.matchForeverId = matchForeverId;
    this.playersInMemorableMoment = playersInMemorableMoment;
    this.archetypeOfMemorableMoment = archetypeOfMemorableMoment;
    this.memorableMomentEncoded = memorableMomentEncoded;
    this.memorableMomentTimestamp = memorableMomentTimestamp;
    this.memoralMomentAutoGeneratedSass = memoralMomentAutoGeneratedSass;
  }
}
