class AssetManifest {
  /**
   * Retrieves the URL for a given asset name.
   * @param {string} assetName - The name of the asset.
   * @returns {string|null} - The URL of the asset, or null if not found.
   */
  static getAssetUrl(assetName) {
    return this.assets[assetName] || null;
  }

  // Asset manifest data
  static assets = {
    archwayPillarLeftPre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/archwayPillarLeftPre.glb",
    archwayPillarRightPre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/archwayPillarRightPre.glb",
    archwayPre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/archwayPre.glb",
    ascensionNebula:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/ascensionNebula.png",
    bagPre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/bagPre.glb",
    bridgeBentPre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/bridgeBentPre.glb",
    bridgeBorkenPiecePre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/bridgeBorkenPiecePre.glb",
    bridgeBrokenPre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/bridgeBrokenPre.glb",
    bridgeWholePre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/bridgeWholeCompressedTest.glb",
    celestialPrismPre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/celestialPrismPre.glb",
    doorClosedPre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/doorClosedPre.glb",
    doorFramePre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/doorFramePre.glb",
    doorLeftPre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/doorLeftPre.glb",
    doorOpenPre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/doorOpenPre.glb",
    doorRightPre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/doorRightPre.glb",
    keyPre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/keyPre.glb",
    levelLarge:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/levelLarge.glb",
    leverBasePre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/leverBasePre.glb",
    leverHandlePre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/leverHandlePre.glb",
    leverWholePre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/leverWholePre.glb",
    leverWholeP1Pre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/leverWholePre.glb",
    lotusPre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/lotusPre.glb",
    purpleNoteBig:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/purpleNoteBig.glb",
    purpleNoteMini:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/purpleNoteMini.glb",
    rotatingLeverPre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/rotatingLeverPre.glb",
    rotatingLeverBasePre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/ratatingLeverBasePre.glb",
    rotatingLeverWholePre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/rotatingLeverWholePre.glb",
    running:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/running.glb",
    spaceSky:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/spaceSky.glb",
    spaceSky2:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/spaceSky2.glb",
    spaceSky3:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/spaceSky3.glb",
    stainedSunShield:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/stainedSunShield.png",
    statue:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/statue.glb",
    tile1Pre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile1Pre.glb",
    tile2Pre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile2Pre.glb",
    tile3Pre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile3Pre.glb",
    tile4Pre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile4Pre.glb",
    tile5Pre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile5Pre.glb",
    tile6Pre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile6Pre.glb",
    wallFramePre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/wallFramePre.glb",
    wallInsidePre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/wallInsidePre.glb",
    wallWholePre:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/wallWholePre.glb",
    archway_lowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/archway_lowPolyCompressed.glb",
    archway_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/archway_lowPoly.glb",
    bagLowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/bagLowPoly.glb",
    bag_lowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/bag_lowPolyCompressed.glb",
    big_wholeCelestialPrism_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/big_wholeCelestialPrism_lowPoly.glb",
    celestialPrism_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/celestialPrism_lowPoly.glb",
    big_wholeCelestialPrism_lowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/big_wholeCelestialPrism_lowPolyCompressed.glb",
    small_celestialPrism_lowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/small_celestialPrism_lowPolyCompressed.glb",
    breakablelWallWhole_LowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/breakablelWallWhole_LowPoly.glb",
    breakablelWallWhole_LowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/breakablelWallWhole_LowPolyCompressed.glb",
    bridgeBent_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/bridgeBent_lowPoly.glb",
    bridgeBent_lowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/bridgeBent_lowPolyCompressed.glb",
    bridgeBrokenPiece_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/bridgeBrokenPiece_lowPoly.glb",
    bridgeBrokenPiece_lowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/bridgeBrokenPiece_lowPolyCompressed.glb",
    bridgeBroken_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/bridgeBroken_lowPoly.glb",
    bridgeBroken_lowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/bridgeBroken_lowPolyCompressed.glb",
    bridgeWhole_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/bridgeWhole_lowPoly.glb",
    bridgeWhole_lowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/bridgeWhole_lowPolyCompressed.glb",
    tile001V1_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile001V1_lowPoly.glb",
    tile001V2_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile001V2_lowPoly.glb",
    tile002V1_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile002V1_lowPoly.glb",
    tile002V2_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile002V2_lowPoly.glb",
    tile003V1_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile003V1_lowPoly.glb",
    tile003V2_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile003V2_lowPoly.glb",
    tile004V1_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile004V1_lowPoly.glb",
    tile005V1_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile005V1_lowPoly.glb",
    tile001V1_lowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile001V1_lowPolyCompressed.glb",
    tile002V1_lowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile002V1_lowPolyCompressed.glb",
    tile002V2_lowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile002V2_lowPolyCompressed.glb",
    tile003V1_lowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile003V1_lowPolyCompressed.glb",
    tile003V2_lowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile003V2_lowPolyCompressed.glb",
    tile004V1_lowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile004V1_lowPolyCompressed.glb",
    tile005V1_lowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/tile005V1_lowPolyCompressed.glb",
    rotatingLeverWhole_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/rotatingLeverWhole_lowPoly.glb",
    pendant_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/pendant_lowPoly.glb",
    lotus_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/lotus_lowPoly.glb",
    key_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/key_lowPoly.glb",
    doorClosed_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/doorClosed_lowPoly.glb",
    doorOpen_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/doorOpen_lowPoly.glb",
    leverWholeP1_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/leverWholeP1_lowPoly.glb",
    leverWholeP2_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/leverWholeP2_lowPoly.glb",
    leverWholeP3_lowPoly:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/leverWholeP3_lowPoly.glb",
    doorClosed_lowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/doorClosed_lowPolyCompressed.glb",
    doorOpen_lowPolyCompressed:
      "https://raw.githubusercontent.com/nicolasbulgarides/testmodels/main/doorOpen_lowPolyCompressed.glb",
  };
}

// Export AssetManifest class globally
window.AssetManifest = AssetManifest;
