class ItemUsageFailurePresets {
  static ITEM_USAGE_FAILURE_PRESETS = new Set([
    "ITEM_NOT_IN_INVENTORY",
    "ITEM_NOT_UNLOCKED",
    "ITEM_REQUIRES_PREMIUM",
    "ITEM_DEPLETED",
    "ITEM_ON_COOLDOWN",
    "ITEM_BAN_SPECIAL",
    "ITEM_EXPIRED",
    "ITEM_BROKEN",
    "ITEM_OWNER_MISMATCH",
    "ITEM_MISCHIEF_PLACEHOLDER",
  ]);
}
